name: build
on: [ pull_request, push ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[skip]')"
    strategy:
      matrix:
        java: [ 17 ]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: zulu

      - name: cache gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/loom-cache
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: give gradlew permissions
        run: chmod +x gradlew

      - name: build
        run: ./gradlew clean assemble

      - name: upload non-merged artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            forge/build/libs/*.jar
            fabric/build/libs/*.jar
            common/build/libs/*.jar

      - name: upload merged artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-merged
          path: build/libs/merged/*.jar